require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'openfeature-sdk.gemspec'

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Gemspec/RequireMFA:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  # TODO re-enable after figuring out what it actually wants
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 2

RSpec/NestedGroups:
  Enabled: false

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false
