module OpenFeature
  module SDK
    module Provider
      module EventEmitter
        def emit_event: (String event_type, ?Hash[Symbol, untyped] details) -> void

        def configuration_attached?: () -> bool

        private

        def attach: (Configuration configuration) -> void
        def detach: () -> void
      end
    end
  end
end
