name: CI

on:
  - push
  - pull_request

jobs:
  rspec:
    runs-on: ${{ matrix.os }}
    name: Ruby ${{ matrix.ruby }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # NOTE: hold off testing other platforms until we start having native dependencies or running into issues on them
          # - macos-latest
          # - windows-latest
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
    env:
      BUNDLE_GEMFILE: Gemfile

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install
      - name: RSpec
        run: bundle exec rspec
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - run: bundle install
      - name: Rubocop
        run: bundle exec rubocop --color
  # check the status of other jobs, so we can have a single job dependency for branch protection
  # https://github.com/community/community/discussions/4324#discussioncomment-3477871
  status:
    name: CI Status
    runs-on: ubuntu-latest
    needs: [rspec, rubocop]
    if: always()
    steps:
      - name: Successful CI
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failing CI
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
