name: CI

on:
  - push
  - pull_request

jobs:
  rspec:
    runs-on: ${{ matrix.os }}
    name: Ruby ${{ matrix.ruby }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # NOTE: hold off testing other platforms until we start having native dependencies or running into issues on them
          # - macos-latest
          # - windows-latest
        ruby:
          - "3.3"
          - "3.2"
          - "3.1"
    env:
      BUNDLE_GEMFILE: Gemfile

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install
      - name: RSpec
        run: bundle exec rspec
      - name: Upload coverage to Codecov
        if: ${{ strategy.job-index == 0 }} # only run codecov on first run
        uses: codecov/codecov-action@v4.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
          file: coverage/coverage.xml
  standard:
    name: Standard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - run: bundle install
      - name: Standard
        run: bundle exec rake standard
  # check the status of other jobs, so we can have a single job dependency for branch protection
  # https://github.com/community/community/discussions/4324#discussioncomment-3477871
  status:
    name: CI Status
    runs-on: ubuntu-latest
    needs: [rspec, standard]
    if: always()
    steps:
      - name: Successful CI
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failing CI
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
